-- ============================================================
-- tenbagger — free-tier Postgres schema (Supabase / Neon)
-- Mirrors the data contract the React app already consumes.
-- Run this once in the Supabase SQL editor (or `psql < schema.sql`).
-- ============================================================

-- One row per instrument. The "snapshot" JSON columns hold the
-- exact shapes the app expects, so the front-end barely changes.
create table if not exists instruments (
  ticker          text primary key,           -- e.g. 'AAPL', 'PETR4.SA'
  name            text not null,
  sector          text,
  country         text,                        -- '🇺🇸 US', '🇧🇷 Brazil'
  currency        text not null default 'USD', -- 'USD','BRL','EUR'
  kind            text,                        -- null | 'etf' | 'reit'
  updated_at      timestamptz not null default now(),

  -- headline fundamentals (flat columns = easy to screen/sort in SQL)
  mkt_cap         numeric,   -- in billions, local currency
  pe              numeric,
  fwd_pe          numeric,
  ps              numeric,
  pb              numeric,
  ev_ebitda       numeric,
  peg             numeric,
  eps_growth      numeric,
  rev_growth      numeric,
  forecast_g      numeric,
  div_yield       numeric,
  payout          numeric,
  debt_eq         numeric,
  roic            numeric,
  roe             numeric,
  roi             numeric,
  net_margin      numeric,
  gross_margin    numeric,
  revenue_m       numeric,   -- millions, local
  ebitda_b        numeric,   -- billions, local
  sector_pe       numeric,
  sector_ps       numeric,
  div_ps          numeric,
  ex_div          text,
  expense_ratio   numeric,   -- ETFs only

  -- balance sheet (billions, local)
  cash            numeric,
  debt            numeric,
  lt_debt         numeric,
  total_liab      numeric,
  total_assets    numeric,
  equity          numeric,
  coverage        numeric,
  recv            numeric,
  inv             numeric,
  phys            numeric,
  ap              numeric,

  -- descriptions
  descr           text,
  descr_long      text,

  -- nested shapes the app reads as-is (JSONB)
  segments        jsonb,     -- [["Platform", 0.78], ...]
  ownership       jsonb,     -- {"Institutional":61,"Insiders":14,...}
  peers           jsonb,     -- [{"n":"...","pe":..,"ps":..,...}]
  phase           jsonb      -- {"kind":"cycle"|"turnaround", ...} or null
);

-- Daily OHLCV price history (one row per ticker per day).
create table if not exists prices (
  ticker          text references instruments(ticker) on delete cascade,
  d               date not null,
  close           numeric not null,
  volume          numeric,
  primary key (ticker, d)
);

-- Annual financial history (revenue/earnings/fcf, ~10y).
create table if not exists financials_annual (
  ticker          text references instruments(ticker) on delete cascade,
  fiscal_year     int  not null,
  revenue         numeric,
  earnings        numeric,
  fcf             numeric,
  primary key (ticker, fiscal_year)
);

-- Insider transactions (SEC Form 4, US tickers).
create table if not exists insider_tx (
  id              bigserial primary key,
  ticker          text references instruments(ticker) on delete cascade,
  filed_at        date,
  insider_name    text,
  role            text,
  is_buy          boolean,
  shares          numeric,
  price           numeric,
  value_usd       numeric
);
create index if not exists idx_insider_ticker on insider_tx(ticker, filed_at desc);

-- Significant-change alerts generated by the collector.
create table if not exists alerts (
  id              bigserial primary key,
  ticker          text references instruments(ticker) on delete cascade,
  created_at      timestamptz not null default now(),
  kind            text,        -- 'Technical' | 'Fundamental'
  direction       int,         -- 1 | 0 | -1
  txt             text
);
create index if not exists idx_alerts_ticker on alerts(ticker, created_at desc);

-- FX rates so the app can convert any local currency to USD.
create table if not exists fx_rates (
  currency        text primary key,   -- 'BRL','EUR',...
  per_usd         numeric not null,   -- units of currency per 1 USD
  updated_at      timestamptz not null default now()
);

-- ---- Row Level Security: allow public READ, block public WRITE ----
-- The collector writes with the service_role key (bypasses RLS).
-- The web app reads with the anon key (read-only).
alter table instruments        enable row level security;
alter table prices             enable row level security;
alter table financials_annual  enable row level security;
alter table insider_tx         enable row level security;
alter table alerts             enable row level security;
alter table fx_rates           enable row level security;

do $$
declare t text;
begin
  foreach t in array array['instruments','prices','financials_annual','insider_tx','alerts','fx_rates']
  loop
    execute format('drop policy if exists "public read" on %I;', t);
    execute format('create policy "public read" on %I for select using (true);', t);
  end loop;
end $$;
